services:
  frontend:
    build:
      context: .
      target: dev-envs
    container_name: frontend
    ports:
      - "80:5173"
      - "5173:5173"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock